apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference-resources
spec:
  containers:
    - image: anyago/online_inference:v1
      name: online-inference-resources
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "125Mi"
          cpu: "250m"
        limits:
          memory: "10Gi"
          cpu: "500m"
