version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    filename: train_pipeline.log
    level: INFO
    formatter: simple
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: simple

loggers:
  __main__:
    level: DEBUG
    handlers: [file_handler]
    propagate: yes

root:
  level: DEBUG
  handlers: [stream_handler]
