logging_config_path: "configs/logging.conf.yml"
input_data_path: "raw_data/heart.csv"
output_model_path: "ml_pipeline/models/model.pkl"
metric_path: "ml_pipeline/models/metrics.json"
splitting_params:
  test_size: 0.2
  random_state: 1984
preprocessing_params:
  scaler: null
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"

